// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimbirsoftWorkshop.WebApi.Data;

namespace SimbirsoftWorkshop.WebApi.Migrations
{
    [DbContext(typeof(BookLibraryContext))]
    partial class BookLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("BookGenres", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 11
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 14
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 17
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 20
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 14
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 17
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 14
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 17
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 14
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 17
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 20
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 18,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 18,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 18,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 19,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 19,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 19,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 20,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 21,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 21,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 22,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 22,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 23,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 23,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 24,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 24,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 25,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 25,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 26,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 26,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 27,
                            GenreId = 30
                        },
                        new
                        {
                            BookId = 27,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 27,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 28,
                            GenreId = 30
                        },
                        new
                        {
                            BookId = 28,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 28,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 29,
                            GenreId = 30
                        },
                        new
                        {
                            BookId = 29,
                            GenreId = 28
                        },
                        new
                        {
                            BookId = 29,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 30,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 30,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 30,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 31,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 31,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 31,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 32,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 32,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 32,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 33,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 33,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 34,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 34,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 34,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 35,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 35,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 35,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 36,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 36,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 36,
                            GenreId = 23
                        },
                        new
                        {
                            BookId = 37,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 37,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 38,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 38,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 39,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 39,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 40,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 40,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 41,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 41,
                            GenreId = 42
                        },
                        new
                        {
                            BookId = 42,
                            GenreId = 39
                        },
                        new
                        {
                            BookId = 42,
                            GenreId = 41
                        },
                        new
                        {
                            BookId = 43,
                            GenreId = 39
                        },
                        new
                        {
                            BookId = 43,
                            GenreId = 41
                        },
                        new
                        {
                            BookId = 44,
                            GenreId = 39
                        },
                        new
                        {
                            BookId = 44,
                            GenreId = 41
                        },
                        new
                        {
                            BookId = 45,
                            GenreId = 39
                        },
                        new
                        {
                            BookId = 45,
                            GenreId = 40
                        },
                        new
                        {
                            BookId = 46,
                            GenreId = 40
                        },
                        new
                        {
                            BookId = 46,
                            GenreId = 41
                        },
                        new
                        {
                            BookId = 47,
                            GenreId = 39
                        },
                        new
                        {
                            BookId = 47,
                            GenreId = 40
                        },
                        new
                        {
                            BookId = 47,
                            GenreId = 41
                        });
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "MiddleName")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Джон",
                            LastName = "Толкин",
                            MiddleName = "Роналд Руэл"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Джордж",
                            LastName = "Оруэлл",
                            MiddleName = "NULL"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Джоан",
                            LastName = "Роулинг",
                            MiddleName = "Кэтлин"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Фрэнк",
                            LastName = "Герберт",
                            MiddleName = "NULL"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Льюис",
                            LastName = "Кэрролл",
                            MiddleName = "NULL"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Клайв",
                            LastName = "Льюис",
                            MiddleName = "Стейплз"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Джордж",
                            LastName = "Мартин",
                            MiddleName = "Рэймонд Ричард"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Стивен",
                            LastName = "Кинг",
                            MiddleName = "Эдвин"
                        });
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Name = "Властелин Колец"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Name = "Хоббит, или Туда и Обратно"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Name = "Хоббит"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Name = "Возвращение Короля"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Name = "Сильмариллион"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Name = "1984"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Name = "Скотный двор"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Name = "Дочь священника"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            Name = "Да здравствует фикус!"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Name = "Дни в Бирме"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Name = "Гарри Поттер и философский камень"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Name = "Гарри Поттер и Тайная комната"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Name = "Гарри Поттер и узник Азкабана"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Name = "Гарри Поттер и Кубок огня"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Name = "Гарри Поттер и Орден Феникса"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Name = "Гарри Поттер и принц-полукровка"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Name = "Гарри Поттер и Дары Смерти"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            Name = "Сказки барда Бидля"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Name = "Фантастические твари и где они обитают"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Name = "Фантастические твари: Преступления Грин-де-Вальда"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 4,
                            Name = "Дюна"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 4,
                            Name = "Мессия Дюны"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 4,
                            Name = "Дети Дюны"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 4,
                            Name = "Бог-Император Дюны"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 4,
                            Name = "Еретики Дюны"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 4,
                            Name = "Капитул Дюны"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 5,
                            Name = "Алиса в Стране чудес"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 5,
                            Name = "Алиса в Зазеркалье"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 5,
                            Name = "Охота на Снарка"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 6,
                            Name = "Лев, Колдунья и Платяной шкаф"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 6,
                            Name = "Принц Каспиан"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 6,
                            Name = "Покоритель Зари, или Плавание на край света"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 6,
                            Name = "Серебряное кресло"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 6,
                            Name = "Конь и его мальчик"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 6,
                            Name = "Племянник чародея"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 6,
                            Name = "Последняя битва"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 7,
                            Name = "Игра престолов"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 7,
                            Name = "Битва королей"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 7,
                            Name = "Буря мечей"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 7,
                            Name = "Пир стервятников"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 7,
                            Name = "Танец с драконами"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 8,
                            Name = "Оно"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 8,
                            Name = "Сияние"
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 8,
                            Name = "Лавка дурных снов"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 8,
                            Name = "Доктор Сон"
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 8,
                            Name = "Мизери"
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 8,
                            Name = "Зелёная миля"
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 8,
                            Name = "Ловец снов"
                        });
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Научная фантастика"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Космическая фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Детективная фантастика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Детская фантастика"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Постапокалипсис"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Фэнтези"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Городское фэнтези"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Стимпанк"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Киберпанк"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Антиутопия"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Повесть"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Зарубежная классика"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Историческая проза"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Русская классическая проза"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Зарубежная классическая проза"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Средневековая классическая проза"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Проза о войне"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Классическая проза"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Проза"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Проза для детей"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Исторические приключения"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Морские приключения"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Русская поэзия"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Детская литература"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Русские сказки"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Сказки народов мира"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Любовные романы"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Остросюжетные любовные романы"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Детективы"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Детские детективы"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Криминальный детектив"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Психологический детектив"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Исторический детектив"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Классический детектив"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Мистика"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Зарубежное фэнтези"
                        });
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.LibraryCard", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("BookReceivingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("BookId", "PersonId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("LibraryCards");

                    b.HasData(
                        new
                        {
                            BookId = 33,
                            PersonId = 2,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 11, 6, 10, 32, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 15,
                            PersonId = 2,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 10, 28, 5, 11, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 29,
                            PersonId = 4,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2021, 10, 16, 0, 39, 24, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 14,
                            PersonId = 2,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 11, 15, 8, 28, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 10,
                            PersonId = 2,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 11, 5, 22, 46, 49, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 21,
                            PersonId = 1,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 10, 20, 16, 27, 14, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 28,
                            PersonId = 4,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 11, 9, 0, 47, 41, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 7,
                            PersonId = 4,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 11, 5, 16, 8, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 27,
                            PersonId = 3,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 10, 18, 4, 30, 48, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            BookId = 12,
                            PersonId = 5,
                            BookReceivingDate = new DateTimeOffset(new DateTime(2022, 10, 19, 22, 20, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "MiddleName", "Birthday")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1971, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Василий",
                            LastName = "Сергеев",
                            MiddleName = "Владимирович"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1975, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Андрей",
                            LastName = "Панфилов",
                            MiddleName = "Артёмович"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1987, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Майя",
                            LastName = "Медведева",
                            MiddleName = "Савельевна"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1984, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Лев",
                            LastName = "Соловьев",
                            MiddleName = "Степанович"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1963, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Макар",
                            LastName = "Зайцев",
                            MiddleName = "Олегович"
                        });
                });

            modelBuilder.Entity("BookGenres", b =>
                {
                    b.HasOne("SimbirsoftWorkshop.WebApi.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK_BookGenres_Books_BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimbirsoftWorkshop.WebApi.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK_BookGenres_Genres_GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Book", b =>
                {
                    b.HasOne("SimbirsoftWorkshop.WebApi.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.LibraryCard", b =>
                {
                    b.HasOne("SimbirsoftWorkshop.WebApi.Entities.Book", "Book")
                        .WithMany("LibraryCards")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimbirsoftWorkshop.WebApi.Entities.Person", "Person")
                        .WithMany("LibraryCards")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Book", b =>
                {
                    b.Navigation("LibraryCards");
                });

            modelBuilder.Entity("SimbirsoftWorkshop.WebApi.Entities.Person", b =>
                {
                    b.Navigation("LibraryCards");
                });
#pragma warning restore 612, 618
        }
    }
}
